services:
  backend:
    build: .
    container_name: studify-backend
    restart: always
    env_file:
      - ../environment/prod/backend/backend.env
    ports:
      - "80:8080"
    networks:
      - mikrus-net

networks:
  mikrus-net:
    external: true