version: "3.8"

services:
  studify-db:
    image: postgres:17
    container_name: studify-db
    restart: always
    env_file:
      - ../environment/local/backend/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: