version: "3"

services:
  backend:
    build: .
    container_name: studify-backend
    restart: always
    env_file:
      - ../environment/prod/backend/db.env
    ports:
      - "8081:8080"
    networks:
      - studify
      - nginx_network

  studify-db:
    image: postgres:17
    container_name: studify-db
    restart: always
    env_file:
      - ../environment/local/backend/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - studify

volumes:
  postgres_data:

networks:
  bot_network:
    external: true
  nginx_network:
    external: true
  studify:
    external: true