version: "3.8"

services:
  studify-db:
    image: postgres:17
    container_name: studify-db
    restart: always
    env_file:
      - ../environment/local/backend/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    env_file:
      - ../environment/local/backend/pg-admin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

#  vault:
#    build: .
#    container_name: vault
#    ports:
#      - "8200:8200"
#    cap_add:
#      - IPC_LOCK
#    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: "root"
#      VAULT_ADDR: "http://127.0.0.1:8200"


volumes:
  postgres_data:
  pgadmin_data: