"""Section to str

Revision ID: 4ab7d33f8e15
Revises: 66483ab3104a
Create Date: 2026-02-16 21:08:06.969420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab7d33f8e15'
down_revision: Union[str, None] = '66483ab3104a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'section',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'section',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
